fix: Use raw files

diff --git a/.github/workflows/apply.yml b/.github/workflows/apply.yml
--- a/.github/workflows/apply.yml
+++ b/.github/workflows/apply.yml
@@ -13,17 +13,6 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Install Nix
-        run: |
-          curl -L https://nixos.org/nix/install | sh
-          . /home/runner/.nix-profile/etc/profile.d/nix.sh
-
-      - name: Build NixOS configuration
-        run: |
-          . /home/runner/.nix-profile/etc/profile.d/nix.sh
-          nix-build '<nixpkgs/nixos>' -A config.system.build.toplevel -I nixos-config=./configuration.nix
-          ls -la ./result
-
       - name: Apply configuration on remote server
         env:
           SSH_PORT: ${{ secrets.SSH_PORT }}
@@ -34,7 +23,7 @@ jobs:
           chmod 600 ./private_key
           which scp || echo "scp command not found"
           which ssh || echo "ssh command not found"
-          zip -r result.zip ./result || echo "Zip failed"
+          zip -r result.zip ./ || echo "Zip failed"
           ssh -o StrictHostKeyChecking=no -i ./private_key github@ovh.mahn.ke -p $SSH_PORT "mkdir -p /tmp/nixos-config-$GITHUB_RUN_ID" || echo "SSH mkdir command failed"
           scp -P $SSH_PORT -o StrictHostKeyChecking=no -i ./private_key result.zip github@ovh.mahn.ke:/tmp/nixos-config-$GITHUB_RUN_ID/ || echo "SCP failed"
           ssh -o StrictHostKeyChecking=no -i ./private_key github@ovh.mahn.ke -p $SSH_PORT "unzip -o /tmp/nixos-config-$GITHUB_RUN_ID/result.zip -d /tmp/nixos-config-$GITHUB_RUN_ID && sudo nixos-rebuild switch -I nixos-config=/tmp/nixos-config-$GITHUB_RUN_ID/result" || echo "SSH command failed"
