fix: Removes typo

diff --git a/.github/workflows/apply.yml b/.github/workflows/apply.yml
--- a/.github/workflows/apply.yml
+++ b/.github/workflows/apply.yml
@@ -29,7 +29,7 @@ jobs:
           SSH_PORT: ${{ secrets.SSH_PORT }}
           SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
         run: |
-          echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > ./private_keyy || echo "Failed to decode private key"
+          echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > ./private_key || echo "Failed to decode private key"
           ls -l ./private_key || echo "Private key file not found"
           chmod 600 ./private_key
           which scp || echo "scp command not found"
